services:
  # Backend API
  - type: web
    name: csv-cleaner-api
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend:/opt/render/project/src/backend/Clean_CSV"

  # Frontend - Static Site
  - type: static
    name: csv-cleaner-frontend
    buildCommand: "npm ci && npm run build"
    staticPublishPath: out
    rootDir: frontend
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NEXT_PUBLIC_API_URL
        value: https://csv-cleaner-api.onrender.com
